apiVersion: batch/v1
kind: Job
metadata:
  generateName: aurora-intensity-processor-job-
spec:
  template:
    spec:
      serviceAccountName: aurora-s3-access
      containers:
      - name: aurora-intensity-processor
        image: 884329724388.dkr.ecr.eu-west-2.amazonaws.com/aurora-intensity-processor:latest
        ports:
        - containerPort: 80
        env:
        - name: BUCKET_NAME
          value: "aurora-explorer-data"
        - name: PREFIX
          value: "aurora-data-raw/"
      restartPolicy: Never
  backoffLimit: 1
