apiVersion: v1
kind: ServiceAccount
metadata:
  name: aurora-access
secrets:
  - name: token-secret
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: token-secret
  annotations:
    kubernetes.io/service-account.name: "aurora-access"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aurora-s3-access
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::884329724388:role/k8s_s3_access_role
