apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: aurora-role
rules:
- apiGroups: ["batch"]
  resources: ["pods", "pods/log", "jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aurora-access-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: aurora-access
  namespace: default
roleRef:
  kind: Role
  name: aurora-role
  apiGroup: rbac.authorization.k8s.io

